const GAME_POINTS = {
    POINTS_PER_DAMAGE: 1,
    POINTS_PER_FRAG: 400,
    POINTS_PER_TEAM_WIN: 2000
};

const STATS = {
    BATTLE: "aHR0cHM6Ly9ub2RlLXNlcnZlci11bmRlci0wZWIzYjlhZWU0ZTMuaGVyb2t1YXBwLmNvbS9hcGkvYmF0dGxlLXN0YXRzLw==",
    STATUS: "aHR0cHM6Ly9ub2RlLXNlcnZlci11bmRlci0wZWIzYjlhZWU0ZTMuaGVyb2t1YXBwLmNvbS9hcGkvc3RhdHVz",
    WS: "bm9kZS1zZXJ2ZXItdW5kZXItMGViM2I5YWVlNGUzLmhlcm9rdWFwcC5jb20="

};

export { GAME_POINTS, STATS };
