const GAME_POINTS = {
    POINTS_PER_DAMAGE: 1,
    POINTS_PER_FRAG: 400,
    POINTS_PER_TEAM_WIN: 2000
};

const STATS = {
    BATTLE: "aHR0cHM6Ly9ub2RlLXNlcnZlci11bmRlci0wZWIzYjlhZWU0ZTMuaGVyb2t1YXBwLmNvbS9hcGkvYmF0dGxlLXN0YXRzLw==",
    IMPORT: "aHR0cHM6Ly9ub2RlLXNlcnZlci11bmRlci0wZWIzYjlhZWU0ZTMuaGVyb2t1YXBwLmNvbS9hcGkvaW1wb3J0Lw==",
    CLEAR: "aHR0cHM6Ly9ub2RlLXNlcnZlci11bmRlci0wZWIzYjlhZWU0ZTMuaGVyb2t1YXBwLmNvbS9hcGkvY2xlYXIv"
};

export { GAME_POINTS, STATS };
